<?php
$nodes = array(
  array(
    'type' => 'course',
    'title' => 'Rotation',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'course',
    'title' => 'Artspace',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'course',
    'title' => 'Bas – solo',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'course',
    'title' => 'Bas – workshop',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
);
