<?php
$nodes = array(
  array(
    'type' => 'course',
    'title' => 'Rotation',
    'body' => '',
    'uid' => 1,
  ),
  array(
    'type' => 'course',
    'title' => 'Artspace',
    'body' => '',
    'uid' => 1,
  ),
  array(
    'type' => 'course',
    'title' => 'Bas – solo',
    'body' => '',
    'uid' => 1,
  ),
  array(
    'type' => 'course',
    'title' => 'Bas – workshop',
    'body' => '',
    'uid' => 1,
  ),
);
