<?php
$nodes = array(
  array(
    'type' => 'course',
    'title' => 'Rotation',
    'body' => '',
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'course',
    'title' => 'Artspace',
    'body' => '',
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),

  array(
    'type' => 'course',
    'title' => 'Sammenspil',
    'field_teaser' => array(
      0 => array(
        'value' => 'Sammenspilsundervisningen er et af de store fag på musiklinien. Undervisningen spænder vidt fra indøvelse af numre og afprøvning af arrangementer over workshops og performance til studieindspilninger og planlægning og gennemførelse af turné med livekoncerter. Man får således prøvet alle de facetter af, som hører til at arbejde med et professionelt band.',
      )
    ),
    'body' => 'Sammenspilsundervisningen er et af de store fag på musiklinien. Det er her man kan samle og bruge mange af de færdigheder man har, og som man får også fra de andre fag (fx. soloundervisning, teori, improvisation, tekst og musik mv.).

Undervisningen spænder vidt fra indøvelse af numre og afprøvning af arrangementer over workshops og performance til studieindspilninger og planlægning og gennemførelse af turné med livekoncerter. Man får således prøvet alle de facetter af, som hører til at arbejde med et professionelt band.

Undervisningen tager udgangspunkt i elevernes niveau og engagement, og det er eleverne der i samarbejde med læreren former og bestemmer indeholdet af undervisningen og former bandet. Der er altså ikke på forhånd lagt nogle rammer og man kan således komme vidt omkring med bandet.

Nogle bands tager udgangspunkt i en bestemt genre, det kan være alt fra rock og pop over funk og soul til jazz og world. Man finder og indstuderer sange og specialiserer sig i genren med dens særlige finesser, karakter og lyd.

Andre blander kortene fordi det er sjovt at arbejde med mange forskellige genrer, eller man leger med genrerne og laver en jazzstandard om til en rock ballade -- eller omvendt.

Andre ser det som noget helt essentiel at komponere og skrive sange selv, og nogle bands vælger helt eller delvist kun at arbejde med eget materiale. Også her er der mange muligheder: Nogle kommer med næsten færdige sange der bare skal finpudses, andre kommer bare med et godt riff eller en tekst som man så arbejder videre med eller man starter helt forfra og jammer sig frem.

Det er altså op til sammenspilsholdet at give bandet karakter, indhold og udtryk og her er engagementet og intensiteten stor. Ofte ender bandet med at blive en lille familie hvor man både musikalsk og socialt er tæt på hinanden.',
    'taxonomy' => array(
      15 => 15,
      16 => 16,
      17 => 17,
      18 => 18,
      19 => 19,
      20 => 20,
      21 => 21,
      22 => 22,
      23 => 23,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'course',
    'title' => 'Linjefag',
    'field_teaser' => array(
      0 => array(
        'value' => 'Dette er et ugentlig 2-lektioners modul som vil ændre indhold i løbet af semestret. I starten vil der være niveaudelt teori/hørelære for alle, men efter ca. 4 gange vil der blive mulighed for, at vælge mellem forskellige linjerelaterede fag.',
      )
    ),
    'body' => 'Dette er et ugentlig 2-lektioners modul som vil ændre indhold i løbet af semestret. I starten vil der være niveaudelt teori/hørelære for alle, men efter ca. 4 gange vil der blive mulighed for, at vælge mellem forskellige linjerelaterede fag. Det kan fx være:

* SDS (Sang, Dans og Spil)
* Teori og hørelære
* "Open Door", "Fri Improvisation", eller Intuitiv Improvisation
* Improvisation
* Sangworkshop
* Rotation',
    'taxonomy' => array(
      15 => 15,
      16 => 16,
      17 => 17,
      18 => 18,
      19 => 19,
      20 => 20,
      21 => 21,
      22 => 22,
      23 => 23,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),

  /* --- BAS -------------------------------------------------------------- */
  array(
    'type' => 'course',
    'title' => 'Soloundervisning',
    'sticky' => 1,
    'field_teaser' => array(
      0 => array(
        'value' => 'På bassen arbejder vi med teknik (fingersætning, håndstilling, klang m.m.), groove/time, akkorder og improvisation/teori, og vi vil arbejde med de meget forskellige roller der er i musikken for bassisten. Der arbejdes med noder og becifring, men også dét at lære musik "på øret".',
      )
    ),
    'body' => 'På bassen arbejder vi med teknik (fingersætning, håndstilling, klang m.m.), groove/time, akkorder og improvisation/teori, og vi vil arbejde med de meget forskellige roller der er i musikken for bassisten. Der arbejdes med noder og becifring, men også dét at lære musik "på øret". At lytte numre eller soloer af og bruge idéerne i en anden sammenhæng eller i egne numre, er en fantastisk metode til at lære at forstå instrumentets muligheder. Det er meget inspirerende og nok det vigtigste værktøj af alle. Soloundervisningen tager naturligvis udgangspunkt i dit niveau. Desuden er det også vigtigt at tilrettelægge undervisningen i forhold til dine aktiviteter i øvrigt på sammenspilsholdet og i fritidsbands på højskolen. Hensigten er at give dig de bedste muligheder for at afprøve metoder og idéer fra soloundervisningen i en aktuel sammenspilssituation. At få inspiration og "blod på tanden" til at gå videre med musikken.',
    'taxonomy' => array(
      15 => 15,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'course',
    'title' => 'Basworkshop',
    'sticky' => 1,
    'field_teaser' => array(
      0 => array(
        'value' => 'Her er alle bassister samlet i en workshop hvor tekniske og musikalske problemer af enhver art kan tages under behandling. Ud over generelle tekniske værktøjer giver faget også et fint udbytte på det sociale plan, idet du får en god mulighed for at lære dine "instrument-kolleger" bedre at kende.',
      )
    ),
    'body' => 'Der ligger et modul med en basworkshop i alle almindelige skemauger. Her er alle bassister samlet i en workshop hvor tekniske og musikalske problemer af enhver art kan tages under behandling. Ud over generelle tekniske værktøjer giver faget også et fint udbytte på det sociale plan, idet du får en god mulighed for at lære dine "instrument-kolleger" bedre at kende, dvs. I får en god forståelse for at hjælpe og inspirere hinanden. Faget ændrer karakter flere gange i løbet af semesteret og byder også på store workshops i salen for alle instrumentlinjerne.',
    'taxonomy' => array(
      15 => 15,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
);
