<?php
$nodes = array(
  array(
    'type' => 'event',
    'title' => 'Generalforsamling',
    'field_teaser' => array(
      0 => array(
        'value' => 'Den årlige generalforsamling med underholdning og køkkenets fantastiske oste/kagebord. For elever og støttekredsmedlemmer.',
      ),
    ),
    'body' => 'Den årlige generalforsamling med underholdning og køkkenets fantastiske oste/kagebord. For elever og støttekredsmedlemmer.',
    'field_date' => array(
      0 => array(
        'value' => '2010-04-20 17:30:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'event',
    'title' => 'Gammelelevtræf',
    'field_teaser' => array(
      0 => array(
        'value' => 'Kom til det traditionsrige årlige elevtræf.',
      ),
    ),
    'body' => 'Kom til det traditionsrige årlige elevtræf.',
    'field_date' => array(
      0 => array(
        'value' => '2010-06-04 14:00:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'event',
    'title' => 'Afslutningskoncert',
    'field_teaser' => array(
      0 => array(
        'value' => 'Afslutningskoncert med sambaoptog, afrikansk tromme og dans, samt elevernes resultat af det halve år på skolen. Det bliver et overflødighedshorn af musik fra alle lande og i afvekslende genre.',
      ),
    ),
    'body' => 'Afslutningskoncert med sambaoptog, afrikansk tromme og dans, samt elevernes resultat af det halve år på skolen. Det bliver et overflødighedshorn af musik fra alle lande og i afvekslende genre.

Gratis entrè.',
    'field_date' => array(
      0 => array(
        'value' => '2010-06-05 11:00:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
);
