<?php
$nodes = array(
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
);
