<?php
$nodes = array(
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'image',
    'title' => 'Placeholder',
    'body' => '',
    'promote' => 1,
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image' => array(
      0 => array(
        'fid' => 1,
        'list' => TRUE,
      ),
    ),
  ),
);
