<?php
$nodes = array(
  array(
    'type' => 'news',
    'title' => 'Nyhed 1',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'news',
    'title' => 'Nyhed 2',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'news',
    'title' => 'Nyhed 3',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'news',
    'title' => 'Nyhed 4',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'news',
    'title' => 'Nyhed 5',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
);
