<?php
$nodes = array(
  array(
    'type' => 'page',
    'title' => 'Forlag',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'page',
    'title' => 'Hverdagen',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'page',
    'title' => 'Praktisk',
    'body' => '',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'page',
    'title' => 'Om skolen',
    'body' => 'Velkommen til Den Rytmiske Højskole. Her kan du læse om vores musikhøjskole, hvor vi tilbyder højskoleliv med udgangspunkt i rytmisk musik, lydteknik og sangskrivning. Vi har professionelle lydstudier og øvelokaler, og undervisning af musikere.

Musik skal dyrkes på højskole, kom og udvid dit musikalske netværk.

Et højskoleophold tager kun et halvt år, men varer hele livet.

Den Rytmiske Højskole ligger ved Vig i Odsherred -- mellem Nykøbing Sj. og Holbæk -- og er centralt placeret uanset hvor i landet du kommer fra.

Det bedste indtryk af skolen får du selvfølgelig ved at besøge os. Hvis du ringer (tlf. 59 360 600) eller mailer i forvejen, sørger vi for en rundvisning.

Læs også vor [myspaceside](http://myspace.com/denrytmiskehojskole) Vi er desuden på facebook www.facebook.dk/denrytmiske og youtube. Find os der.',
    'field_image_ref' => array(
      0 => array(
        'nid' => 1,
      ),
    ),
  ),
  array(
    'type' => 'page',
    'title' => 'Kort',
    'body' => 'På kortet ovenfor kan du se hvordan du finder os.',
    'field_map' => array(
      0 => array(
        'value' => '<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=jyderupvej+18,4560&amp;sll=55.869147,11.228027&amp;sspn=6.56401,14.128418&amp;hq=&amp;hnear=Jyderupvej+18,+4560,+Vig,+Denmark&amp;ie=UTF8&amp;ll=55.88648,11.572037&amp;spn=0.134783,0.291824&amp;z=11&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=jyderupvej+18,4560&amp;sll=55.869147,11.228027&amp;sspn=6.56401,14.128418&amp;hq=&amp;hnear=Jyderupvej+18,+4560,+Vig,+Denmark&amp;ie=UTF8&amp;ll=55.88648,11.572037&amp;spn=0.134783,0.291824&amp;z=11&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>',
      ),
    ),
  ),
);
