<?php
$nodes = array(
  array(
    'type' => 'profile',
    'title' => 'Hans J Hansen',
    'body' => 'Hans startede på skolen som projektansat, hvor han bl.a. lavede kurser/projektforløb for andre højskolelærere, Danmarks radio, og teaterteknikkere mv., for skolens kursusvirksomhed.

Siden 98 har han været almindelig deltidsansat og er nu fuldtidsansat.

Han underviser i underviser i fællesfag, videoproduktion og ArtSpace.

Desuden er HJH ansvarlig for skolens netværk. Han er uddannet ingeniør, har speciale i kunstig intelligens og er gal med billeder. Kig bare løs på den rytmiskes galleri -- Hans har taget de fleste billeder.',
    'taxonomy' => array(
      9 => 9, // valgfag
      25 => 25, // anden lærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Underviser i Grafisk kommunikation/Artspace, Photoshop, forskellige it-relaterede fag, og filosofi. Hans er også højskolens it-ansvarlige.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Jannik Jensen',
    'body' => 'Jannik er glad for at spille bas.',
    'taxonomy' => array(
      15 => 15, // bas
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Jannik er meget glad for at spille bas.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Stig Kaufmanas',
    'body' => 'Stig underviser i lydteknik.',
    'taxonomy' => array(
      15 => 15, // bas
      18 => 18, // klaver
      19 => 19, // lydteknik
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Stig underviser i lydteknik.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Pia Boda',
    'body' => 'Underviser i sammenspil, teori/hørelære og saxofon.

Pia er uddannet på Det Rytmiske Konservatorium i 91 med saxofon som hovedinstrument og har siden været ansat på Den Rytmiske Højskole sideløbende med sit musikerliv. På højskolen er hun blæserlærer og underviser p.t. i sammenspil og teori/hørelære, men tilbyder i perioder valgfag som f.eks. improvisation og rytmeworkshop.

Pia Boda spiller saxofon og fløjte og bor i København. Hun er født i Hollywood samme år som Charlie Parker døde. Er nu ikke direkte hans reinkarnation, da hun foretrækker salsa og lyrisk jazz frem for bebop.

Pia har muskuløse ben, da hun altid cykler i København og slæber sine saxofoner op på 4. sal. Hun er vældig glad for at bo oppe i lyset i hjertet af det berygtede Vesterbro og vil ikke bytte, men er glad for at Emil, hendes søn har lært at gå op af trapper. Pia mødte sin italienske mand Marco på Musikkonservatoriet og hans første invitation var på hjemmelavet "Pasta Bolognese". Siden har hun været meget glad for italiensk mad.

Før Pia gik på Konservatoriet, tog hun en uddannelse som snedker, så hun selv kunne lave sine saxofonblade og sine møbler. Når man træder ind i hendes lejlighed, ser man straks, at hun har et lidenskabeligt forhold til træ, hvorfor hun måtte blive træblæser. Denne lidenskab for træ gælder også de svenske skove i Småland, hvor hun i mange år har holdt ferie og en gang har bygget et hus i Ryssby.

I tidens løb er rejserne gået til mange andre steder end Sverige. Pia er lidt af en kosmopolit. I bus fra Danmark gennem Tyrkiet, Iran, Pakistan, Indien til Nepal i Himalaya. Så blev det Grønland for at bygge fåre stalde. Siden har musikken bl.a. ført hende til Canada, USA, Brasilien og nu hvor hun er blevet "gift" med Italien, er det blevet til rigtig mange besøg og turné virksomhed i hendes andet hjemland.

Pia har foruden klarinetten netop fået endnu et nyt biinstrument, nemlig Kazoo, hvor hun indtil videre kun kan spille Sinatra\'s: "I did it my Way".

Musikalsk virke som musiker/komponist:

1979-81 Hexehyl Bigband. Jazz, rock, latin fusion under ledelse af Hanne Rømer
1983-85 Tyrkis Bigband. Tyrkisk fusion under ledelse af Atilla Engin
1983-86 Dr. Livingstone and the Presumers. Afrikansk musik
1985-87 Bigband 85. Nyere bigband musik af og ved Lars Togeby
1986 Studierejse til USA I 3 MDR.. Dick Grove School of Music
1987-91 Ballerup Bigband. Traditionel Bigband musik med skiftende dirigenter.

1991 Uddannes med saxofon som hovedfag på Det Rytmiske Konservatorium
1989-94 Four or Less. Egen trio med egne kompositioner og jazz/latin standards.
1990-97 Marco Spallanzan/Pia Boda Kvintet. Spiller 8 år i træk på Copenhagen Jazzfestival, tur-nevirksomhed i Danmark og Italien
1991-fortsat Underviser på Den Rytmiske Højskole i Vig. Sammenspil, hørelære/teori, saxofon, blæser workshop.
1991 Komponerer og spiller musik til Teaterkavaleriets opsætning af H.C.Branner\'s Søskende.
1992 Arbejds/studieophold i Banff Center of Arts i Canada. Spiller koncert med bl.a. Kenny Whee-ler, Reggie Workmann og Keith Copeland. Spiller med "Brad\'s Second Line Brassband" i Banff og omegn.
1992 Præsenterer egen musik i Canada med kvintettet "Danish Pastry"
1992-93 Anaconda. Brasil jazz.
1993+94 Deltager i Siena Jazz. Spiller med ledende Italienske musikere som Enrico Rava, Franco d’Andrea og Paulo Fresu.
1994 Turnerer med Teater Cantabile 2 med forestillingen "Helvede" af Dante.
1995 Studierejse til Brasilien og USA. Koncerter i San Fransisco med bl.a. John Tchicai.
1984-94 Underviser på Musikskoler i Albertslund, Ishøj og Køge.
Leder Bigbandet på Køge Musikskole i et år
1993 Sommerstævne På Den Rytmiske Højskole. Soulsammenspil.
1994-2000 Underviser i "Benhård" hørelære/teori på Rytmisk Center.
1996 Studerer på Åbent Universitet. Musikhistorie
1996 "Havannaexspress" (Salsaorkester med herboende cubanske musikere)
1996 Autumn Jazzfestival: "Makiko Hirabayashi/ Pia Boda duo"
1996 Reikjavik Jazzfestival. Koncert med Kvindebigbandet "April Ligth Orchestra"
1997/98 Studere på Åbent Universitet: Koralharmonisering og Korledelse.
DJBFA kursus i instrumentation af Strygekvartet og blæserkvintet.
1997 Udgiver CD med "Spallanzani og Boda Kvintet".
1997 Eddie Skoller\'s Bellevue show "Interneddie". Kapelmester:Jens Krøjer.
1998 Trio med Keld Lauritsen, Marco Spallanzani spiller på Copenhagen Jazzfestival

1998 Bliver mor til Emil. Det er stort!!!

1999 CD med "Son en Taya" (Salsaorkester med herboende cubanere)
1999 Spiller med "Saxpac" Svensk kvinde sax kvartet.. Forestillingen "Best in show" på Victoriateatern i Malmø med komikerparret "Åse og Gertrud". www.saxpac.nu
1999 Tango Workshop og koncert i Rom med den argentinske pianist: Hugo Aisemberg.
2000-2002 Koncerter med bl.a. "Son en Taya", "Havannaexpress" og "Latinmonster".
2000-fortsat Underviser i hørelære på MGK i Ishøj.
2001 Efteruddannelse. Årskursus i hørelære på Det Rytmiske Konservatorium.
2002 Efteruddannelse. Årskursus i komposition på Rytmisk Konservatorium.
2002 "Chasing Pixies". Kvintet med musik af Pia Boda og Makiko Hirabayashi.
2003 Lærer på Familie sommer stævnet på Den Rytmiske Højskole og underviser sammenspil for børn og forældre.
2003 "Cabaret" på Gladsaxe Teater. Spiller sax, fløjte og klarinet i kvindeorkestret under ledelse af Sasha Dupont.
2006 Underviser fortsat på DRH og MGK ishøj

Musikalske medspillere der har krydset min vej: John Tchicai, Benita Haastrup, Lisbeth Diers, Kaare Munkholm, Kasper Ludvigsen, Ole Rasmussen, Jacob Jensen, Peter Hansen, Sasha Dupont, Keld Lauritsen, Esben Duus, Makiko Hirabayashi, Stefan Pasborg, Thommy Andersson, Lars Bo Enselman, Peter Danemo, Carlitos Gomez, Humberto Gomez og ikke mindst alle mine musikalske kolleger på Den Rytmiske Højskole

…og tak til nogle af mine lærere: Thomas Frank, Bob Rockwell, Uffe Marcussen, Krølle, Hugo Rasmussen, Frederik Lundin, Thomas Clausen, Django Bates, Kenny Wheeler, Reggie Workman, Enrico Rava, Franco d\'Andrea, Paulo Fresu, Wolfgang Muthspiel, Brian Blade.',
    'taxonomy' => array(
      16 => 16, // blæs
      27 => 27, // musik
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Pia er saxofonist. Hun har solo, workshop og forskellige valgfag.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Søren Reiff',
    'body' => 'Søren Reiff guitarist, producer, komponist, forfatter og foredragsholder.

Søren Reiff underviser i produktion og komposition samt guitarworkshop.

De fleste her i Danmark kender ham sikkert bedst som den skaldede, smilende guitarist og kapelmester i TV-programmerne "Husk lige Tandbørsten, "Så\' det lørdag" og "Den store Klassefest".

Siden 2001 har Reiff spillet og tourneret både i Europa og USA med amerikanske musikere og solister, blandt andet med David Garfield, Alex Ligertwood, Gregg Bisonette og Los Lobotomys.

Reiff har også spillet med Chaka Khan, David Sandborn, Robert Palmer, Randy Crawford, og fra skandinavien Lisa Nilsson, Marie Bergmann, Sanne Salomonsen, Thomas Helmig, Søs Fenger og mange flere.

I 2003 udgav Reiff solo-albummet Funky Flavas, hvor positive anmeldere sammenligneda ham med guitarister som Joe Satriani, Larry Carlton, George Benson og John Scofield. I 2008 udkommer efterfølgeren i form af albummet L.A.Flavas.

Reiff har sideløbende med sin karriere som guitarist indspillet og produceret musik med Michael Ruff, Mike Stern, Alberte, Kaya Brüel, MC Einar, Nikolaj Pilot Christensen, Marie Carmen Koppel og mange flere.

Ligesom Søren også har skrevet og produceret musik i sit studie DaRoof, til reklamer, undervisningsmateriale, kortfilm og tv-programmer.

Desuden har Søren Reiff skrevet de anmelderroste guitar undervisningsbøger "Reiffs riffs" og "Reiffs rytmer", "Reiffs riffs II" samt "Gode råd er guld værd" en bog om livet musikbranchen.

Du kan også læse mere på www.REIFF.dk .

Søren har været medlem af bestyrelsen 1998-2004.',
    'taxonomy' => array(
      17 => 17, // guitar
      21 => 21, // SP
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Underviser i guitar, guitarworkshop og på sangskriver- og producerlinjen.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Anna Stengade',
    'body' => 'Anna er uddannet sanger og musik- og bevægelseslærer fra Rytmisk Musikkonservatorium i København i 2008.

Hun underviser i SDS, Tekst og musikværksted og linjefag.

Anna er sangskriver, og skriver især til sit eget band ”Anna Stengade” (myspace.com/annastengade) men også til andre solister i samarbejde med andre sangskrivere og producere.

”Jeg har selv gået på Den Rytmiske tilbage i foråret 2000. Det var her jeg fandt ud af at jeg ville satse alt på sangskrivningen og synge mine egne sange. Det var så dejligt et ophold at jeg nu er vendt tilbage, bare på den anden side af skrivebordet.”',
    'taxonomy' => array(
      20 => 20, // sang
      21 => 21, // SP
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Underviser i sang, dans og spil (SDS), Tekst og musikværksted og linjefag.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'René Damgaard',
    'body' => 'Underviser i sammenspil, guitar og workshop.

Egentligt ville René have været trommeslager, men efter at have hørt Carlos Santana spille blev det guitaren han kastede sig over. Det gjorde han med stor iver, først nogle år i musikskole og senere med privatlærer, men i det store hele er René selvlært. Han har nu spillet guitar i mere end 20 år og har som guitarist været vidt omkring både musikalsk og geografisk. Genremæssigt har han været det meste igennem fra rock og pop over salsa, funk og latin til fusion og jazz. Geografisk har han spillet så forskellige steder som Sovjet, Frankrig, Sverige, Bahrain, Estland, Skotland, Jylland og Ganløse.

I dag går Renés musikalske liv hovedsageligt i to retninger: \'Improvisationsmusik\' (Jazz/Fusion) hvor han både spiller og skriver musik; og \'Balle\' (Pop/Rock) hvor han både spiller og tjener penge. Til dagligt er han beskæftiget i flere forskellige musikalske sammenhænge fx: Damgaard/Eskestad Duo (Jazz), Chromatones.dk (Fusion) og Partyband(s) (Pop/Rock).

René har været ansat på højskolen siden 1997 og har undervist/underviser i sammenspil, soloundervisning (guitar), improvisation, musikalsk kuffert (teori/hørelærer), lejrbålsguitar, instrumental workshop mm.

Når René ikke er på højskolen eller er \'ude at spille\' så er han på Østerbro hvor han bor sammen med sin kæreste Nanja og sin søn Sofus. Der er også her (på Østerbro) han har købt en gammel hestestald som han har indrettet til øvelokale.',
    'taxonomy' => array(
      17 => 17, // guitar
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Underviser i sammenspil, guitar og guitarworkshop.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Rasmus Grossel',
    'body' => 'Rasmus underviser bl.a. i sammenspil, trommer og trommeworkshop.

Mange års studie-, live- og teatererfaring bl.a.:

Karina Kappel, Allain Apoloo, Api people, Annette Bjergfeldt, Jacob Andersen (stjerne for en aften vinder), Poul Banks, Clubheads, Etta Cameron, Burning Red Ivanhoe, Secret Oyster, Monique, Sebastian, Franka, Taylors Univers, Esben Just, Jacob Rønne band, Tommy Kenter , Young comets og div. studie projekter + mange, mange, mange flere.

Jeg har modtaget undervisnig på ”Drummers collective”, - flere gange og tager jævnligt tilbage på kortere inspirations ture, er netop hjemvendt fra en kortere tur hvor jeg modtog undervisning af bl.a. den cubaske trommeslager Ignacio Berroa

Derudover har jeg gået hos Bent Lylloff, Freddy Gruber, Ed Thigpen, Pete Lockett i London og i de yngre dage hos Jonas Johansen, Niels Ratzer, Søren Frost m.fl. Jeg har også studeret i en længere periode i Ghana, Vestafrika.

Aktuelt er jeg i gang med pladeindspilninger med Allain Appaloo, Api People, og skal i efteråret medvirke i Ledreborg slotskoncerterne i DR opsætning af Sebastians ”Skatteøen” med radiounderholdningsorkestret.',
    'taxonomy' => array(
      23 => 23, // trommer
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Underviser bl.a. i sammenspil, trommer og trommeworkshop. ',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Niels Jørgensen',
    'body' => 'Underviser i sammenspil, teori/hørelære, brugsklaver og div. valgfag  fx. økologi.

Er forfatter til drh-forlags første udgivelse ”Brugsklaver - Nyt, Nemt & Nørdet."

Spiller keyboards i souldivers.com.

Tidligere medejer af Gaya Musik i Holbæk med filial på højskolen. Tidligere afdelingsleder i Musikskole, underviser på Danmarks Pædagogiske Universitet samt censor på lærerseminariet, hvor Niels også selv er uddannet.',
    'taxonomy' => array(
      18 => 18, // klaver
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Underviser i sammenspil, teori/hørelære og div. valgfag som f.eks. økologi og brugsklaver. ',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
);
