<?php
$nodes = array(
  array(
    'type' => 'profile',
    'title' => 'Hans J Hansen',
    'body' => '',
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Jannik Jensen',
    'body' => 'Jannik er glad for at spille bas.',
    'taxonomy' => array(
      15 => 15, // bas
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Jannik er meget glad for at spille bas.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'profile',
    'title' => 'Stig Kaufmanas',
    'body' => 'Stig underviser i lydteknik.',
    'taxonomy' => array(
      15 => 15, // bas
      18 => 18, // klaver
      19 => 19, // lydteknik
      27 => 27, // musiklærer
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Stig underviser i lydteknik.',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
);
