<?php
$nodes = array(
  array(
    'type' => 'teaser',
    'title' => 'Musiklinie',
    'body' => '[Bas](http://drh.local/bas)
[Guitar](http://drh.local/guitar),
[Sang](http://drh.local/sang)
[Blæser](http://drh.local/blaeser)
[Klaver](http://drh.local/klaver)
[Tromme](http://drh.local/trommer)',
    'field_image_front_on' => array(
      0 => array(
        'fid' => 2,
        'list' => TRUE,
      ),
    ),
    'field_image_front_off' => array(
      0 => array(
        'fid' => 3,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'teaser',
    'title' => 'Tekniklinie',
    'body' => 'Tekniklinie',
    'field_image_front_on' => array(
      0 => array(
        'fid' => 2,
        'list' => TRUE,
      ),
    ),
    'field_image_front_off' => array(
      0 => array(
        'fid' => 3,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'teaser',
    'title' => 'Producerlinie',
    'body' => 'Producerlinie',
    'field_image_front_on' => array(
      0 => array(
        'fid' => 2,
        'list' => TRUE,
      ),
    ),
    'field_image_front_off' => array(
      0 => array(
        'fid' => 3,
        'list' => TRUE,
      ),
    ),
  ),
  array(
    'type' => 'teaser',
    'title' => 'Sommerkurser',
    'body' => 'Sommerkurser',
    'field_image_front_on' => array(
      0 => array(
        'fid' => 2,
        'list' => TRUE,
      ),
    ),
    'field_image_front_off' => array(
      0 => array(
        'fid' => 3,
        'list' => TRUE,
      ),
    ),
  ),
);
