<?php
$nodes = array(
  array(
    'type' => 'teaser',
    'title' => 'Musiklinie',
    'body' => '[baslinie](http://drh.local/content/bas)
[blæser](http://drh.local/content/blaeser)
[guitar](http://drh.local/content/guitar)',
    'uid' => 1,
  ),
  array(
    'type' => 'teaser',
    'title' => 'Tekniklinie',
    'body' => 'Tekniklinie',
    'uid' => 1,
  ),
  array(
    'type' => 'teaser',
    'title' => 'Producerlinie',
    'body' => 'Producerlinie',
    'uid' => 1,
  ),
  array(
    'type' => 'teaser',
    'title' => 'Sommerkurser',
    'body' => 'Sommerkurser',
    'uid' => 1,
  ),
);
