<?php
$nodes = array(
  array(
    'type' => 'topic',
    'title' => 'Bas',
    'body' => "På baslinjen vil du få soloundervisning på bas, basworkshop og spille bas på et sammenspilshold. Derudover er der en lang række fag, nogle fælles for alle, andre er valgfag.

Udenfor undervisningstiden er alle vores faciliteter åbne, så der fx kan øves, spilles i fritidsbands eller laves studieindspilninger.

Når du vælger baslinjen er der rigtig mange emner at tage fat på. Lad mig derfor nævne et par af de vigtigste emner: Vi vil komme til at arbejde med forskellige teknikker så som venstre-/højrehåndsteknik, hvordan du får en god klang/lyd og skalateknik så du kan finde rundt på bassen. Groove er selvfølgelig en vigtig del, og da solospil/improvisation og akkorder er blevet en del af det at spille bas, skal vi også arbejde med det.

## Udstyret

Som Bassist kan du bla. møde Mesa Boogie bass 400+, SWR 350 X, Hartke 3500, Ampeg og Eden's nye Nemesis serie mm.",
    'taxonomy' => array(
      15 => 15,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Musiklinie',
    'body' => 'Med musik som hovedfag skal du vælge en instrumentlinie.

På instrumentlinien vil du få soloundervisning på dit instrument, instrumentworkshop og spille dit instrument på et sammenspilshold. Derudover er der en lang række fag, nogle fælles for alle, andre er valgfag.

Du bliver sat på et af de 7-10 sammenspilshold, som sammensættes udfra ønsker og kunnen. Vi niveaudeler ikke -- vi laver hold der lyder godt!

Normalt er der 60-70 musikelever, og 8-16 teknikere, men med sang- og producerlinien regner vi med at begge grupper bliver lidt mindre. Vi har ikke plads til mere end 78 elever -- med et par tre-sengs værelser.',
    'field_teaser' => array(
      0 => array(
        'value' => 'Som musiker på den rytmiske kommer du til at spille på et af 7-10 sammenspilshold, som sammensættes udfra jeres ønsker og kunnen. Vi niveaudeler ikke - vi laver hold der lyder godt!',
      ),
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Trommer',
    'body' => '',
    'taxonomy' => array(
      23 => 23,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Sang',
    'body' => '',
    'taxonomy' => array(
      20 => 20,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Klaver',
    'body' => '',
    'taxonomy' => array(
      18 => 18,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Guitar',
    'body' => '',
    'taxonomy' => array(
      17 => 17,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Blæser',
    'taxonomy' => array(
      16 => 16,
    ),
    'body' => '',
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Sommerkurser',
    'body' => 'Det er altid spændende at bruge sin ferie på noget aktivt. At tage på sommerhøjskole er måske noget af det mest udviklende, der findes. Sammen med andre kursister udfordres du fagligt og socialt. Dine meninger og holdninger prøves af, samtidig med at du udvikler nye "værktøjer" indenfor det faglige felt, der lige netop interesserer dig. Samtidig er det vigtigt at gøre sig klart, at der netop er tale om højskolekurser. Derfor vil du også komme til at beskæftige dig med andre emner end det valgte fokus. Disse emner vil dog først blive fastlagt kort før kursusstart. Dette begrundet i ønsket om at kunne være impulsiv, hvis noget vigtigt skulle dukke op. Omfanget af disse aktiviteter fremgår af ugeskemaet. Det skulle glæde os meget, hvis du valgte et sommerkursus på Den Rytmiske Højskole. Vi vil gøre alt for at det vil være en god beslutning.

Sommerkursusprogrammet 2010:

Blæsere- og slagtøjskursus 2010  (Uge 26, med start søndag 27. juni)
Kurset er for alle, der har lyst til at spille i et stort harmoniorkester/Concert Band. Der vil både være instrumental- og sammenspilinstruktion for træ - og messingblæsere samt slagtøjsspillere.

Sang, kor og livsglæde 2010 (Uge 27, med start søndag 4. juli)
På besøg i sangens verden: Korsang, udtryk og energi.
En uge med såvel hyggeligt samvær som faglige input med livsglæden som den røde tråd.

Rytmisk sommer 2010 (Uge 28 og 29, med start søndag 11. juli)
Det traditionsrige stævne med sammenspil, lydteknik, sang og sangskrivning i inspirerende form.

Den musikalske familie 2010 - UDSOLGT! (Uge 30, med start søndag 25. juli)
Det  årlige inspirerende familiekursus med bl.a. tegne/maleværksted, musikalsk legestue, sammenspil, friluftsliv og masser af sjove fællesaktiviteter.


Vi arbejder på foldere og tilmeldingsblanketter, hvis du vil vide mere kan du nedenfor læse om kurserne i 2009. Næste års kurser vil tage udgangspunkt i dette års.
Ved hvert kursus kommer der et link til download af en folder. Hvis du hellere vil have folderen tilsendt kan du kontakte højskolens kontor. Tlf. 5936 0600, eller mail.',
    'taxonomy' => array(
      22 => 22,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Sang- og producerlinie',
    'body' => "Hvad kom først? Hønen eller ægget...

I musikkens verden kan man spørge om det er den seje produktion, det fængende omkvæd eller den gode melodi som kommer først?Det er umuligt at svare entydigt på sådan et spørgsmål. Ofte skabes tidens musik i et tæt samarbejde mellem sangskriver og producer; og tit er solisten også med i denne kreative proces, derfor er det oplagt at Den Rytmiske Højskole har en linje som fokuserer på skabelsen og produktionen af nutidig musik. 

Linjen henvender til dig som har lyst til fordybe dig i sangskrivning og de moderne musikproduktionsmetoder. 

Det betyder ikke noget om du tidligere har skrevet og/eller produceret musik. Det har heller ingen betydning hvilket instrument du spiller - om du er sanger som spiller lidt guitar eller klaver, lydtekniker eller computer-haj, der allerede har arbejdet med forskellige musikprogrammer, eller musiker som har spillet i flere år, men som nu gerne vil fokusere mere på at skrive musik. 

Det har til gengæld stor betydning at du har lyst til arbejde med processen omkring det at skrive og skabe musik, samtidigt med der også fokuseres på færdige produktioner og sange, og vigtigst at du har mod på både at komponere og skrive tekster, samt lyst til at arrangere både andres og egen musik, eftersom der arbejdes med alle disse forskellige emner i undervisningen. 

Omdrejningspuntet for undervisningen og hele den kreative proces er skolens mange studiefaciliteter. Her får du mulighed for at idéudvikle og komponere egen musik, indspille, mixe og meget meget mere.

Dette er en proces hvor mange elementer kan indgå. Ved siden af undervisningsforløbet, der vil komme rundt i forskellige arbejdsscenarier omkring at skrive, komponere og producere musik, kan du selv vælge om du vil lægge vægten på melodi/komposition, tekstskrivning, indspilning og bearbejdning af musik, arrangement, harmonisering, lyddesign og remixes... 

Kort sagt det at være komponist, sangskriver eller producer.

## Undervisningen:

### Fælles workshops

Vi arbejder med hele sangskrivnings processen - hvordan du arbejder bedst i en kreativ proces og hvordan du udvikler dine ideer til færdige sange og produktioner. Meget naturligt arbejder vi derfor også med alle de forskellige faser i forløbet fra den første spæde idé til et nummer, og til det er færdigt produceret og indspillet.

Det betyder vi gennemgår indspilningsteknikker og produktionsværktøjer.

Vi vil kigge på hvordan man indspiller og bearbejder musik. Vi vil se på hvordan nutidens teknologi er en aktiv og lettilgængelig inspirator og sparringspartner.

Gennem øvelser og eksempler vil du hurtigt få et godt kendskab til tidens teknikker og redskaber, så du kan udnytte skolens mange studier og tekniske mulighederne optimalt i din kreative proces.

Ved hjælp af referenceeksempler vil vi se hvordan moderne musik er bygget op og hvordan produktioner benytter beats, samples, effekter og plug-ins. Ved at kigge nærmere på forskellige produktioner, får vi også set på forskellige måder at komponere, arrangere og producere, samt hvordan nutidige studier er bygget op.

Derudover vil vi komme til at arbejde med genrekundskab, musikhistorie, arrangement samt andre relevante emner.

### Solo-sessions

I starten af forløbet vil ovennævnte fællesworkshops blive kombineret med at du selv sidder ved et af skolens musik-computer-setups og prøver den nye viden af, med råd og vejledning fra læreren i de teknikker som kan danne fundamentet for dine fremtidige produktioner og indspilninger.

Når de første introduktioner til skolens udstyr, programmer og studier er klaret vil du efterfølgende få masser af muligheder for at sidde og fordybe dig i egne produktioner hvor du bliver undervist og rådgivet i lige præcis det du har brug for i forhold til det du arbejder med.

Disse ”solo-sessions” kan bedst sammenlignes med en blanding af sangernes eller instrumentalisternes solo- og sammenspils-undervisning.

Derudover vil du selvfølgelig hele tiden kunne arbejde sammen med de andre elever på musik- og lydtekniklinjen, både i undervisningsrelaterede projekter, og i de projekter du laver i fritiden. Udstyret er til rådighed døgnet rundt.

## Gruppe-projekter/samarbejde

Udover undervisning gennem fællesworkshops, eller hvor du sidder alene og arbejdder med de nye ting vil vi arbejde i mindre grupper, hvor 2 eller flere elever går sammen. Enten efter oplæg og opgaver fra lærerne, eller fordi det er oplagt at arbejde sammen i specifikke faser i kompositionsprocessen eller til visse typer produktioner.

Du vil altså både modtage undervisning i grupper og på en-mands-hånd, ligesom du kommer til at skulle arbejde sammen i grupper og andre gange sidde selv med projekter.

## Andre relevante oplysninger

Linjen er ikke nødvendigvis sammensat som et traditionelt sammenspilshold, men kan for eksempel bestå af nogle sangere, som spiller lidt guitar eller klaver, nogle bassister, keyboardspillere, trommeslagere eller andre instrumentalister, måske dj's, rappere eller andre som interesserer sig for det at skrive, komponere, indspille og producere musik.

Som tidligere skrevet er linjen temmelig bred, og du har muligheden for at fordybe dig i forskellige arbejdsområder indenfor sangskrivning og musikproduktion. Det kan du gøre yderligere gennem de valgfag som skolen tilbyder og som vil passe godt til det du ønsker at styrke. Nogle af de valgfag som vil være oplagte at kombinere med linje-undervisningen kunne være: ”Tekstværkstedet”, ”Teori/Hørelære”, ”Brugsklaver”, ”Rytmeworkshop” eller ”Bifagsguitar”.

## Sidste relevante oplysninger

Selvom holdopstillingen kan være sammensat på en utraditionel måde, er det stadig tanken at linjens elever deltager på skolens koncertturnéer, som alle andre.

Måske 3 sing-a-song-writere på en turné, mens en dj og en human-beat-box kan være første act på en anden turné, hvor filmkomponistens musik og video ses mellem 2 sammmenspilsholds set på en tredje turné, mulighederne er uendelige og varierer nødvendigvis fra semester til semester. Skolen har altid 4 turnéer af sted hvert halve år.

## Udstyr

Vi har 1 stort mere analogt orienteret indspilningsstudie med flere indspilningsrum, 1 stort digitalt studie, 2 mindre digitale studier med indspilningsrum, samt 10 produktionssatelitter i form af iMac's som er opsat til musikproduktion.

Alle disse steder arbejdes der både med programmerne ProTools og LogicStudio.",
    'taxonomy' => array(
      21 => 21,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'Linjen henvender til dig som har lyst til fordybe dig i sangskrivning og de moderne musikproduktionsmetoder.',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
  array(
    'type' => 'topic',
    'title' => 'Tekniklinie',
    'body' => 'På tekniklinjen får du mulighed for at opbygge et indgående kendskab til analog og digital inspilningsteknik i skolens 4 studier. Vi arbejder bl.a. med de forskellige faser i studieindspilningen, herunder grundlyd, hovedtelefon-mix til musikerne, overdubs og mixdown med effekter og dynamics. Endvidere mikrofonopstilling, signalvej i studierne, mixerpultens opbygning og krydsfelt, gennemgang af mikrofontyper og karakteristiker.

Af teoretiske emner kan nævnes akustik og lydens udbredelse i et rum, og spektral gehør som træner evnen til at identificere de enkelte frekvenser i frekvensområdet.

Et overordnet mål med lydteknikundervisningen er samarbejdet mellem musikere og teknikere. Fokus er lagt på indspilning af skolens orkestre som gennem hele semestret kommer på besøg i lydstudierne. I løbet af semestret vil der være flere emne-uger med et særligt indhold, også her vil studieindspilning være i centrum.

Efter den første måned med basis-forløb vil du få mulighed for at tage et "kørekort" til skolens 2 store studier. Det vil give dig fuld adgang studierne.

Vi arbejder også med PA-lyd. I salen og caféen kommer du til at lave opstilling til koncerter. Du vil som tekniker på Den Rytmiske Højskole kunne opbygge rutine indenfor livelyd, både front-of-house og monitor på scenen, med henblik på turné-ugen hvor musikere og teknikere rejser rundt i Danmark og spiller koncerter på andre skoler.',
    'taxonomy' => array(
      19 => 19,
    ),
    'field_created' => array(
      0 => array(
        'value' => '2010-04-17 10:18:00',
        'timezone' => 'Europe/Copenhagen',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
    'field_teaser' => array(
      0 => array(
        'value' => 'På tekniklinjen får du mulighed for at opbygge et indgående kendskab til analog og digital indspilningsteknik i skolens 4 studier.',
      ),
    ),
    'field_image_ref' => array(
      0 => array(
        'nid' => 20,
      ),
    ),
  ),
);
